# Generated by Django 3.2.9 on 2021-11-29 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_inf', models.CharField(max_length=50)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BaseProduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sales_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('like_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(default='123456', max_length=20)),
                ('sex', models.CharField(default='m', max_length=1)),
                ('login_status', models.BooleanField(default=0)),
                ('subscribe_num', models.IntegerField(default=0)),
                ('fan_num', models.IntegerField(default=0)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('is_default_child', models.BooleanField(default=False)),
                ('parent_produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.baseproduce')),
            ],
            options={
                'unique_together': {('child_name', 'parent_produce')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.users')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('images', models.ImageField(default=None, upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.users')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.users'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default=None, max_length=10)),
                ('paymentTime', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall.address')),
                ('produce', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.produce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.users')),
            ],
            options={
                'unique_together': {('user', 'produce', 'paymentTime')},
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.baseproduce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.users')),
            ],
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(db_column='fan_id', on_delete=django.db.models.deletion.CASCADE, related_name='fan', to='shoppingmall.users')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='shoppingmall.users')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.produce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.users')),
            ],
        ),
        migrations.AddField(
            model_name='baseproduce',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shoppingmall.category'),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_images', models.ImageField(default=None, upload_to='')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.baseproduce')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.users'),
        ),
        migrations.CreateModel(
            name='ProduceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.baseproduce')),
            ],
            options={
                'unique_together': {('produce', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='ProduceComment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shoppingmall.order')),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('comment_like_num', models.IntegerField(default=0)),
                ('star', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('base_produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.baseproduce')),
            ],
        ),
    ]
