# Generated by Django 3.2.9 on 2021-12-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='icon',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
