# Generated by Django 3.2.9 on 2021-12-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0003_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduce',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='商品是否上架'),
        ),
        migrations.AddField(
            model_name='produce',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='produce',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='produce_buy', to='shoppingmall.produce'),
        ),
        migrations.AlterUniqueTogether(
            name='produce',
            unique_together={('order', 'parent_produce'), ('child_name', 'parent_produce')},
        ),
        migrations.RemoveField(
            model_name='produce',
            name='is_default_child',
        ),
    ]
