# Generated by Django 3.2.9 on 2021-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0004_auto_20211203_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='child_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
