# Generated by Django 3.2.9 on 2021-12-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0005_alter_produce_child_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='parent_produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='shoppingmall.baseproduce'),
        ),
    ]
