# Generated by Django 3.2.9 on 2021-12-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0007_post_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='comment_user',
            new_name='user',
        ),
    ]
