# Generated by Django 3.2.9 on 2021-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0009_alter_users_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimages',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='produceimages',
            name='image',
            field=models.ImageField(default=None, upload_to='produce_imgs'),
        ),
    ]
